{
  "data" : {
    "viewer" : {
      "subscription" : {
        "__typename" : "Subscription",
        "isActive" : true,
        "expiresTime" : 1686027161000000,
        "purchaseType" : "apple_iap"
      },
      "uid" : 2210454361,
      "stopButtonMinBuildNumber" : 999999,
      "availableBots" : [
        {
          "isSystemBot" : true,
          "isDeleted" : false,
          "hasMultiplayerFeed" : true,
          "__typename" : "Bot",
          "nickname" : "capybara",
          "botId" : 3002,
          "displayName" : "Sage",
          "picture" : {
            "localName" : "openaiAvatar",
            "__typename" : "LocalBotImage"
          },
          "hasSuggestedReplies" : true,
          "hasClearContext" : true,
          "contextClearWindowSecs" : 1800,
          "allowsUserCreation" : false,
          "isDown" : false,
          "isApiBot" : false,
          "id" : "Qm90OjMwMDI=",
          "model" : "capybara",
          "shareLink" : "https://poe.com/sage",
          "hasWelcomeTopics" : true,
          "disclaimer" : "This bot may make incorrect statements. It does not have knowledge of events after 2021. ",
          "viewerIsFollower" : false,
          "messageLimit" : {
            "dailyBalance" : null,
            "monthlyBalanceRefreshTime" : null,
            "canSend" : true,
            "dailySent" : 0,
            "resetTime" : 1685664000000000,
            "shouldShowRemainingMessageCount" : false,
            "numMessagesRemaining" : null,
            "shouldShowSubscriptionRationale" : false,
            "dailyLimit" : null,
            "__typename" : "MessageLimit",
            "monthlyLimit" : null,
            "monthlyBalance" : null
          },
          "description" : "Good in languages other than English, and also in programming-related tasks. Powered by gpt-3.5-turbo."
        },
        {
          "isSystemBot" : true,
          "isDeleted" : false,
          "hasMultiplayerFeed" : true,
          "__typename" : "Bot",
          "nickname" : "beaver",
          "botId" : 3007,
          "displayName" : "GPT-4",
          "picture" : {
            "localName" : "Avatar_GPT_Blue",
            "__typename" : "LocalBotImage"
          },
          "hasSuggestedReplies" : true,
          "hasClearContext" : true,
          "contextClearWindowSecs" : 1800,
          "allowsUserCreation" : false,
          "isDown" : false,
          "isApiBot" : false,
          "id" : "Qm90OjMwMDc=",
          "model" : "beaver",
          "shareLink" : "https://poe.com/gpt-4",
          "hasWelcomeTopics" : true,
          "disclaimer" : "This bot may make incorrect statements. It does not have knowledge of events after 2021. ",
          "viewerIsFollower" : false,
          "messageLimit" : {
            "dailyBalance" : 1,
            "monthlyBalanceRefreshTime" : 1686009600000000,
            "canSend" : true,
            "dailySent" : 0,
            "resetTime" : 1685664000000000,
            "shouldShowRemainingMessageCount" : false,
            "numMessagesRemaining" : 601,
            "shouldShowSubscriptionRationale" : false,
            "dailyLimit" : 1,
            "__typename" : "MessageLimit",
            "monthlyLimit" : 600,
            "monthlyBalance" : 600
          },
          "description" : "OpenAI's most powerful model. Stronger than ChatGPT in quantitative questions (math and physics), creative writing, and many other challenging tasks. Availability is currently limited."
        },
        {
          "isSystemBot" : true,
          "isDeleted" : false,
          "hasMultiplayerFeed" : true,
          "__typename" : "Bot",
          "nickname" : "a2_2",
          "botId" : 1008,
          "displayName" : "Claude+",
          "picture" : {
            "localName" : "Avatar_Orange_Gradient",
            "__typename" : "LocalBotImage"
          },
          "hasSuggestedReplies" : true,
          "hasClearContext" : true,
          "contextClearWindowSecs" : 1800,
          "allowsUserCreation" : false,
          "isDown" : false,
          "isApiBot" : false,
          "id" : "Qm90OjEwMDg=",
          "model" : "a2_2",
          "shareLink" : "https://poe.com/claude%2B",
          "hasWelcomeTopics" : true,
          "disclaimer" : "This bot may make incorrect statements. It does not have knowledge of events after 2021. ",
          "viewerIsFollower" : false,
          "messageLimit" : {
            "dailyBalance" : 3,
            "monthlyBalanceRefreshTime" : 1686009600000000,
            "canSend" : true,
            "dailySent" : 0,
            "resetTime" : 1685664000000000,
            "shouldShowRemainingMessageCount" : false,
            "numMessagesRemaining" : 1003,
            "shouldShowSubscriptionRationale" : false,
            "dailyLimit" : 3,
            "__typename" : "MessageLimit",
            "monthlyLimit" : 1000,
            "monthlyBalance" : 1000
          },
          "description" : "Anthropic's most powerful model. Particularly good at creative writing."
        },
        {
          "isSystemBot" : true,
          "isDeleted" : false,
          "hasMultiplayerFeed" : true,
          "__typename" : "Bot",
          "nickname" : "a2",
          "botId" : 1006,
          "displayName" : "Claude-instant",
          "picture" : {
            "localName" : "Avatar_Placeholder_Orange",
            "__typename" : "LocalBotImage"
          },
          "hasSuggestedReplies" : true,
          "hasClearContext" : true,
          "contextClearWindowSecs" : 1800,
          "allowsUserCreation" : true,
          "isDown" : false,
          "isApiBot" : false,
          "id" : "Qm90OjEwMDY=",
          "model" : "a2",
          "shareLink" : "https://poe.com/claude-instant",
          "hasWelcomeTopics" : true,
          "disclaimer" : "This bot may make incorrect statements. It does not have knowledge of events after 2021. ",
          "viewerIsFollower" : false,
          "messageLimit" : {
            "dailyBalance" : null,
            "monthlyBalanceRefreshTime" : null,
            "canSend" : true,
            "dailySent" : 0,
            "resetTime" : 1685664000000000,
            "shouldShowRemainingMessageCount" : false,
            "numMessagesRemaining" : null,
            "shouldShowSubscriptionRationale" : false,
            "dailyLimit" : null,
            "__typename" : "MessageLimit",
            "monthlyLimit" : null,
            "monthlyBalance" : null
          },
          "description" : "Anthropic’s fastest model, with strength in creative tasks. Features a context window of 9k tokens (around 7,000 words)."
        },
        {
          "isSystemBot" : true,
          "isDeleted" : false,
          "hasMultiplayerFeed" : true,
          "__typename" : "Bot",
          "nickname" : "chinchilla",
          "botId" : 3004,
          "displayName" : "ChatGPT",
          "picture" : {
            "localName" : "Avatar_Placeholder_Blue",
            "__typename" : "LocalBotImage"
          },
          "hasSuggestedReplies" : true,
          "hasClearContext" : true,
          "contextClearWindowSecs" : 1800,
          "allowsUserCreation" : true,
          "isDown" : false,
          "isApiBot" : false,
          "id" : "Qm90OjMwMDQ=",
          "model" : "chinchilla",
          "shareLink" : "https://poe.com/chatgpt",
          "hasWelcomeTopics" : true,
          "disclaimer" : "This bot may make incorrect statements. It does not have knowledge of events after 2021. ",
          "viewerIsFollower" : false,
          "messageLimit" : {
            "dailyBalance" : null,
            "monthlyBalanceRefreshTime" : null,
            "canSend" : true,
            "dailySent" : 0,
            "resetTime" : 1685664000000000,
            "shouldShowRemainingMessageCount" : false,
            "numMessagesRemaining" : null,
            "shouldShowSubscriptionRationale" : false,
            "dailyLimit" : null,
            "__typename" : "MessageLimit",
            "monthlyLimit" : null,
            "monthlyBalance" : null
          },
          "description" : "Powered by gpt-3.5-turbo."
        }
      ],
      "id" : "Vmlld2VyOjA=",
      "__typename" : "Viewer",
      "updateSuggestedReplyStyle" : false,
      "macosMinEncouragedVersion" : 11,
      "hasCompletedMultiplayerNux" : false,
      "iosMinEncouragedVersion" : 124,
      "showEmailFirstOnPoeLoginPage" : false,
      "enableThemePreferenceSetting" : true,
      "shouldForceSubscriptions" : false,
      "showPoeDebugPanel" : false,
      "isEligibleForSubscriptions" : true,
      "appRatingPromptInfo" : null,
      "primaryEmail" : "68s9gjx2gv@privaterelay.appleid.com",
      "showBotInfoCardMinBuildNumber" : 999999,
      "longUserMessageTruncationMinBuildNumber" : 999999,
      "enableCodeSyntaxHighlightingInMarkdown" : false,
      "poeUser" : {
        "id" : "UG9lVXNlcjoyMjEwNDU0MzYx",
        "viewerIsFollowedBy" : false,
        "uid" : 2210454361,
        "profilePhotoURLTiny" : null,
        "handle" : null,
        "profilePhotoURLSmall" : null,
        "isFollowable" : false,
        "profilePhotoURLLarge" : null,
        "bio" : null,
        "creationTime" : 1685418796892225,
        "viewerIsFollowing" : false,
        "fullName" : "Marol Lee",
        "isPoeOnlyUser" : true,
        "profilePhotoURLMedium" : null,
        "__typename" : "PoeUser"
      },
      "enableExploreBotsPage" : true,
      "linkifyText" : false,
      "allowImagesForApiBots" : false,
      "macosMinSupportedVersion" : 11,
      "inAppPurchasesIneligibleRegions" : [
        "BRA",
        "CHN",
        "MEX",
        "RUS",
        "URY",
        "KEN",
        "IDN",
        "DZA",
        "AGO",
        "ARG",
        "AZE",
        "BMU",
        "BOL",
        "BWA",
        "CYM",
        "TCD",
        "COD",
        "CRI",
        "DOM",
        "ECU",
        "SLV",
        "SWZ",
        "FJI",
        "GAB",
        "GTM",
        "GUY",
        "HND",
        "IRQ",
        "ISR",
        "JAM",
        "JOR",
        "KWT",
        "LBN",
        "LBY",
        "MDG",
        "MWI",
        "MRT",
        "MUS",
        "MNG",
        "MNE",
        "MAR",
        "MOZ",
        "MMR",
        "NIC",
        "MKD",
        "PAK",
        "PAN",
        "PNG",
        "PRY",
        "PER",
        "PHL",
        "QAT",
        "RWA",
        "SEN",
        "LKA",
        "TZA",
        "TTO",
        "TUN",
        "TKM",
        "VEN",
        "ZMB",
        "AFG",
        "AIA",
        "ATG",
        "BLZ",
        "BEN",
        "BTN",
        "VGB",
        "BRU",
        "BFA",
        "CPV",
        "COG",
        "CIV",
        "DMA",
        "GMB",
        "GRD",
        "GNB",
        "LAO",
        "LBR",
        "MDV",
        "MLI",
        "FSM",
        "MSR",
        "NAM",
        "NRU",
        "NPL",
        "NER",
        "PLW",
        "STP",
        "SYC",
        "SLE",
        "SLB",
        "KNA",
        "LCA",
        "VCT",
        "SUR",
        "TON",
        "TCA",
        "VUT",
        "YEM"
      ],
      "removeInviteLimit" : false,
      "enableButtonComponents" : false,
      "enableSuggestedReplies" : true,
      "allowImages" : false,
      "iosMinSupportedVersion" : 100,
      "autoGeneratedHandle" : "marollee",
      "enableUserCreatedBots" : true,
      "enableStopButtonDelayByTime" : false,
      "messageVoiceOutputMinBuildNumber" : 999999,
      "removeWelcomeTopicsVariant" : "show_first_day"
    }
  },
  "extensions" : {
    "is_final" : true
  }
}
